---
title: "Data wrangling"
author: "PL"
date: "10/22/2018"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```

load the gapminder dataset
```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the dataset
gapminder #looks at all the data
head(gapminder) #gives first 6 rows of data
tail(gapminder) #gives last 6 rows of data

head(gapminder, 10) #gives first 10 rows

str(gapminder)  #gives structure of the data
summary(gapminder) #give stats by column, best for numerical
install.packages("skimr")
skimr::skim(gapminder) # more elaborate overview of data
names(gapminder) # gives column names
dim(gapminder) # dimensions - # of columns
nrow(gapminder) # of rows
# reverse-engineer dim
c(nrow(gapminder), ncol(gapminder)) #combines 2 values
```


##Dplyr

```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country == "United States")
filter(gapminder, country %in% c("Mexico", "Peru", "Brazil"))
filter(gapminder, country == "Mexico", year == 2002)
filter(gapminder, country == "Mexico", year > 2000)

# find mean life expectancy in Sweden
sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)



```



```{r}
# select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) #exclude unwanted columns

```


```{r}
# use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
# too verbose - need to condense it down and avoid unneeded variables

```

The pipe operator will change your life

```{r}
gapminder %>% head() # equivalent to head(gapminder)
gapminder %>% head(3) # just 3 rows

gap_cambodia <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp)
# or... finally:
gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select (-continent, -lifeExp)
# keyboard shortcut for pipe is Cmd-Shft-M!

```



```{r}
# Mutate adds new variables:
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)
```

challenge - find max gdpPerCap of Egypt and Vietnam, 
solution: create a new column, calculate gdp, visually find max.
```{r}
gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap, 
         maxgdp = max(gdp))
  
  

```
** Tuesday Session**
## 'group_by()' groups!

```{r}
## with mutate
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()
View(gap_grouped)

## with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup()
View(gap_summarized)
```

## 'arrange()' arranges columns

```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp)) # desc() orders by gdp, high to low 

View(gap_summarized) 
```

## joining datasets!

```{r}

## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore a bit
co2 %>% head()
co2 %>% dim() #12 obs

## create a new gapminder variable with only 2007 data
gap_2007 <- gapminder %>% 
  filter(year == 2007)
gap_2007 %>% dim() #142 observations

## left join
lj <- left_join(gap_2007, co2, by = "country") 
# variable name "country" needs "" whenever joining

# can also code it like this:
lj <- gap_2007 %>% 
  left_join(co2, by = "country")


# right join gap_2007 to co2
rj <- right_join(gap_2007, co2)
View(rj) # will show what it defaulted to in red, in console
rj <- right_join(gap_2007, co2, by = "country") #being explicit
View(rj)

# can change order of join, but still do left_join, and results look like right join...
lj2 <- left_join(co2, gap_2007, by = "country")
View(lj2)

```










```{r}

```


















